[package]
name = "cryptus"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
bcrypt = "0.15.1"
clap = { version = "4.0", features=['cargo']}
rand = "0.8.5"
rpassword = "7.3.1"
sha2 = "0.10.8"
zeroize = "1.8.0"
